VERSION = "2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME = "Lightsail Network"
ORG_URL = "https://lightsail.network/"
ORG_GITHUB = "lightsail-network"
ORG_OFFICIAL_EMAIL = "team@lightsail.network"
ORG_KEYBASE = "overcat"

[[PRINCIPALS]]
name = "Jun Luo"
email = "4catcode@gmail.com"
github = "overcat"

[[VALIDATORS]]
ALIAS = "lightsail-network-1"
DISPLAY_NAME = "Lightsail Network 1"
HOST = "core-live-a.lightsail.network:11625"
PUBLIC_KEY = "GCAT2DUDAW7FSNEX4O2TKH3X2UN6RM6LJGBS4FVV6UN62ROBPWYDMYY5"
HISTORY = "https://core-live-a-history.lightsail.network/"
