VERSION = "2.0.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME = "Lightsail Network"
ORG_URL = "https://lightsail.network/"
ORG_GITHUB = "lightsail-network"
ORG_OFFICIAL_EMAIL = "team@lightsail.network"

[[PRINCIPALS]]
name = "Jun Luo"
email = "4catcode@gmail.com"
github = "overcat"
